// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrationDI
{
    public partial class TestTable
    {
        public string Test1 { get; set; }
        public short? Test2 { get; set; }
        public int Id { get; set; }
    }
}